import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const repoRoot = process.cwd();
const protoRoot = resolve(repoRoot, "open-simulation-interface");
const generatedDir = resolve(repoRoot, "generated");
const descriptorDefinitionsDir = resolve(repoRoot, "generated/type-descriptors");

type DescriptorTarget = {
  proto: string;
  pb: string;
  constName: string;
};

const descriptorTargets: DescriptorTarget[] = [
  {
    proto: "osi_groundtruth.proto",
    pb: "osi3_groundtruth_descriptor.pb",
    constName: "osi3GroundTruthDescriptor",
  },
  {
    proto: "osi_sensorview.proto",
    pb: "osi3_sensorview_descriptor.pb",
    constName: "osi3SensorViewDescriptor",
  },
  {
    proto: "osi_sensordata.proto",
    pb: "osi3_sensordata_descriptor.pb",
    constName: "osi3SensorDataDescriptor",
  },
  {
    proto: "osi_sensorviewconfiguration.proto",
    pb: "osi3_sensorviewconfiguration_descriptor.pb",
    constName: "osi3SensorViewConfigurationDescriptor",
  },
  {
    proto: "osi_hostvehicledata.proto",
    pb: "osi3_hostvehicledata_descriptor.pb",
    constName: "osi3HostVehicleDataDescriptor",
  },
  {
    proto: "osi_trafficcommand.proto",
    pb: "osi3_trafficcommand_descriptor.pb",
    constName: "osi3TrafficCommandDescriptor",
  },
  {
    proto: "osi_trafficcommandupdate.proto",
    pb: "osi3_trafficcommandupdate_descriptor.pb",
    constName: "osi3TrafficCommandUpdateDescriptor",
  },
  {
    proto: "osi_trafficupdate.proto",
    pb: "osi3_trafficupdate_descriptor.pb",
    constName: "osi3TrafficUpdateDescriptor",
  },
  {
    proto: "osi_motionrequest.proto",
    pb: "osi3_motionrequest_descriptor.pb",
    constName: "osi3MotionRequestDescriptor",
  },
  {
    proto: "osi_streamingupdate.proto",
    pb: "osi3_streamingupdate_descriptor.pb",
    constName: "osi3StreamingUpdateDescriptor",
  },
];

function runProtoc(protoPath: string, outputPath: string): void {
  const bufScript = resolve(repoRoot, "node_modules/@bufbuild/buf/bin/buf");
  if (!existsSync(bufScript)) {
    throw new Error(`Buf CLI wrapper not found at ${bufScript}. Run 'yarn install' first.`);
  }

  console.log(`[generate-schema-definitions] Building descriptor set for ${protoPath}`);
  const result = spawnSync(
    process.execPath,
    [bufScript, "build", protoPath, "--as-file-descriptor-set", "-o", outputPath],
    { cwd: repoRoot, stdio: "inherit" },
  );

  if (result.error != null) {
    throw result.error;
  }

  if (result.status !== 0) {
    throw new Error(`buf build failed with exit code ${result.status}`);
  }
}

function toUint8ArrayTs(constName: string, bytes: Buffer): string {
  const lines: string[] = [];
  lines.push("// Generated by scripts/generate-schema-definitions.ts. Do not edit manually.");
  lines.push(`export const ${constName} = new Uint8Array([`);
  for (let i = 0; i < bytes.length; i += 16) {
    const chunk = bytes.subarray(i, Math.min(i + 16, bytes.length));
    lines.push(`  ${Array.from(chunk).join(", ")},`);
  }
  lines.push("]);");
  lines.push("");
  return lines.join("\n");
}

function main(): void {
  console.log("[generate-schema-definitions] Starting schema descriptor generation");
  mkdirSync(generatedDir, { recursive: true });
  mkdirSync(descriptorDefinitionsDir, { recursive: true });
  console.log(
    `[generate-schema-definitions] Ensured output directories: ${generatedDir}, ${descriptorDefinitionsDir}`,
  );

  for (const target of descriptorTargets) {
    runProtoc(join(protoRoot, target.proto), join(generatedDir, target.pb));
  }

  for (const target of descriptorTargets) {
    const descriptorBytes = readFileSync(join(generatedDir, target.pb));
    const outputPath = join(descriptorDefinitionsDir, target.pb.replace(/\.pb$/, ".ts"));
    console.log(
      `[generate-schema-definitions] Writing TypeScript descriptor ${outputPath} from ${target.pb}`,
    );
    writeFileSync(outputPath, toUint8ArrayTs(target.constName, descriptorBytes), "utf8");
    rmSync(join(generatedDir, target.pb), { force: true });
    console.log(
      `[generate-schema-definitions] Removed temporary file ${join(generatedDir, target.pb)}`,
    );
  }

  console.log(
    `[generate-schema-definitions] Completed ${descriptorTargets.length} descriptor definition(s)`,
  );
}

main();
